---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.0.118

verifier:
  name: inspec

platforms:
  - name: mwrock/Windows2016

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes: